### ISSUE TITLE
Create index could create data-dir instead of failing if it doesn't exist

### ISSUE THREAD

**Issue by ddelemeny** [quickwit-oss/quickwit#1138]
When installing quickwit from source repository and using it via `cargo run`, the first example of the getting started guide ('index create') will fail because there's no qwdata directory.

Instead of assuming that the install script was executed, the index create command could just handle the initial setup.

**Comment by guilload** [comment]
Pros:
- saves one `mkdir` and improves the UX

Cons:
- performs an implicit side effect
- may create a directory in an undesired location since we default to the current working directory
- may create the directory with the wrong user, group, and permissions, which may create other issues down the road

I personally am not a fan of programs that create files and directories in locations other than `/var/lib/<program name>` or `~/.<program name>/` without explicit permission.

In addition, the issue should not happen for our Docker and `.tar.gz` releases if packaged properly. For development, I believe fixing #1352 should help and we can also add `qwdata` to our `.gitignore` file.

**Comment by guilload** [comment]
I think this [comment](https://github.com/quickwit-oss/quickwit/issues/1352#issuecomment-1114429781) also lays out good arguments for closing this issue.
