### ISSUE TITLE
Index problem

### ISSUE THREAD

**Issue by demingry** [quickwit-oss/quickwit#1167]
HI, I have trouble with indexing this doc:

```
{
    "IP": "1.1.1.1",
    "Location": {
        "Continent": "Oceania",
        "Country": "Australia",
        "Country_Code": "AU"
    },
    "Autonomous_system": {
        "ASN": 13335,
        "Description": "CLOUDFLARENET",
        "BGP_Prefix": "1.1.1.0/24",
        "Country_Code": "US"
    },
    "Operating_system": {
        "Identifier": ""
    },
    "Dns": {
        "Names": [
            "www.phonedive.com",
            "aljennings.com",
            "cpanel.lecturatarotamarres.com",
            "targetsignal.com"
        ],
        "Records": {
            "1zp.cn": {
                "Record_type": "A",
                "Resolved_at": "2021-12-26T12:30:44.655527900Z"
            },
            "8020creditrepairbusiness.com": {
                "Record_type": "A",
                "Resolved_at": "2022-01-09T12:30:45.406307935Z"
            }
        },
        "Reverse": null
    },
    "RunningServices": [
        {
            "Service_name": "DNS",
            "Extended_service_name": "DNS",
            "Port": 53,
            "Transport_protocol": "UDP",
            "Banner": "",
            "Software": null,
            "Running": {
                "Server_type": "FORWARDING",
                "Resolves_correctly": true,
                "R_code": "SUCCESS"
            }
        }
    ]
}
```

I've read doc many times, but I cannot do it. Help index_config.yaml,  Appreciate!

**Comment by PSeitz** [comment]
Could you add more information. 
Do you get an error or do you have unexpected search results? 
What does your index_config look like?

**Comment by fmassot** [comment]
@demingry your use case is interesting, I bet your documents are semi-structured in the sense that you don't know in advance all the field names like this one `8020creditrepairbusiness.com`.

We don't support currently semi-structured documents but this will be the case in the next Quickwit version that will be shipped in April.

If you want to test indexing with the current version, it will require some preprocessing on the document so that you can declare all possible fields in the index config file. 

My advice would be to wait for 0.3 version or to work on a simplified mapping to make some tests.
