### ISSUE TITLE
[Papercut] Fix some CLI inconsistencies

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#1320]
- [ ] Remove `data-dir` option when not necessary
- [ ] Fix the display order of some commands (1. `config`, 2. `index`, 3. `source`/`split`, 4. other options)
- [ ] Make required options such as `config` or `index` actually required
- [ ] Set default values with `default_value`
- [ ] Add aliases (`ls`, `rm`, ...) whenever possible

**Comment by kalil-pelissier** [comment]
Hi, I'm new to Quickwit and would like to contribute.
I thought that this issue would be a good one to start but I have the feeling that these tasks have already been done.

Can I have a confirmation that this issue is still relevant?
If it's not the case, I will go for another one.

Thanks :smile:.

**Comment by guilload** [comment]
Hi @kalil-pelissier, 

This issue is up for grabs. You can go ahead and submit a PR, I'll happily review your work. Feel free to ping me on [Discord](https://discord.quickwit.io) if need some context.
