### ISSUE TITLE
Fix the split store

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#2022]
Is the split store broken?

**Comment by fulmicoton** [comment]
We have two different subjects here: 
- is it efficient?
- is it broken?

After landing https://github.com/quickwit-oss/quickwit/pull/1980 we will have only one merge pipeline for all pipelines and the split store will be shared (very that last assertions).

**Comment by fulmicoton** [comment]
@evanxg852000 I think @guilload had some clear idea on the solution.

**Comment by fulmicoton** [comment]
Actually I'll pick that ticket @evanxg852000 and tackle it tomorrow

**Comment by guilload** [comment]
Some pointers for a solution:
- one global split store per node held by the indexing service.
- split store is responsible for enforcing the space quota.
- on startup, the split store GCs the dangling indexes AND splits.
- split store keeps track of splits in a binary heap of split IDs; since split IDs are ULIDs, the split store is aware of the order of creation of the splits
- when the space quota is reached, the split store evicts at the top of the heap. (I wonder whether we should also take the size of the splits into account since the cost of downloading is higher for those cache misses)

Some scenarios seem to indicate that we need to run the GC logic periodically:
- index or split deletions
- indexing pipeline(s) for an index no longer scheduled on node
- indexing pipeline(s) complete successfully (backfill)
- crashed indexing pipelines stuck in a retry loop
- ...

There are also cases where a split can stay in limbo; for instance, a split will never be merged (index still exists, but indexing pipelines are now scheduled on another node, and no incoming documents). We may want to evict splits older than some threshold. FTR, for almost all the components of the data platform stack at Airbnb (Airflow, YARN, Spark shuffle service, ...), we ended up putting a CRON job in place to remove temporary files older than x hours.


Refinements
- avoid caching mature splits
- evict merged splits

**Comment by fulmicoton** [comment]
Finding other problems with the current code. Right now we do move splits out of the store when they are accessed, but we don't update stats at this point.
