### ISSUE TITLE
Indexing service auto restart

### ISSUE THREAD

**Issue by yangjinming1062** [quickwit-oss/quickwit#2034]
**Is your feature request related to a problem? Please describe.**
Merge service failure caused indexing service to be interrupted.

**Describe the solution you'd like**
I wish the indexing service will auto restart.

**Describe alternatives you've considered**
the `quickwit run` command stop.

**Additional context**
Add any other context or information about the feature request here.
![image](https://user-images.githubusercontent.com/30614179/192923892-2fc5c62e-1876-457c-a609-fa1f2a05a3d4.png)

**Comment by fmassot** [comment]
Thanks for the report @yangjinming1062. The indexing service should normally restart, in the logs, you can see the `gen=2` which means that the indexing pipeline on the index `traceback` has already restarted 2 times. With a merge publisher error, the pipeline should restart again, and in the logs, you should see after the error a log with `spawn_pipeline` and `gen=3`.

Can you give your quickwit binary version ?

**Comment by yangjinming1062** [comment]
> Thanks for the report @yangjinming1062. The indexing service should normally restart, in the logs, you can see the `gen=2` which means that the indexing pipeline on the index `traceback` has already restarted 2 times. With a merge publisher error, the pipeline should restart again, and in the logs, you should see after the error a log with `spawn_pipeline` and `gen=3`.
> 
> Can you give your quickwit binary version ?

Thanks, my quickwit version is : 0.3.1

**Comment by fmassot** [comment]
Ok. Can you give me the full logs (you attach a logs.txt file to the issue)? I want to be sure that the indexing pipeline has stopped and for which reason it has.

**Comment by yangjinming1062** [comment]
OK, the log file size of 10MB, so I make a zip file
[quickwit.zip](https://github.com/quickwit-oss/quickwit/files/9673581/quickwit.zip)

**Comment by fmassot** [comment]
Thanks! In this file I can see that everything is running fine. There is no restart in the logs. As you can note, the `gen` or pipeline generation remains at `2`. 

In quickwit, we distinguish the `IndexingService` that is just a service that spawns indexing pipelines on demand.

The real stuff happens in the actor `IndexingPipeline`. This actor is spawning all the indexing pipeline actors. If one of them fails, all those actors will be killed, and the `IndexingPipeline` actor will respawn new actors once all old actors have existed.

 So when you see `exit_status` of publisher/merger/uploader/..., this is expected.

There is one log that I don't really like in your screenshot, this is the "Failed to replace splits". This kind of logs should not happen unless there is a bug somewhere or you removed manually a split for example. I cannot say much here as I would need the full history of the index. If you manage to reproduce this bug, it's worth opening an issue and put all the logs you have on this.

@yangjinming1062 if this explanation is sufficiently clear, let me know so that I can close the issue.

**Comment by yangjinming1062** [comment]
> Thanks! In this file I can see that everything is running fine. There is no restart in the logs. As you can note, the `gen` or pipeline generation remains at `2`.
> 
> In quickwit, we distinguish the `IndexingService` that is just a service that spawns indexing pipelines on demand.
> 
> The real stuff happens in the actor `IndexingPipeline`. This actor is spawning all the indexing pipeline actors. If one of them fails, all those actors will be killed, and the `IndexingPipeline` actor will respawn new actors once all old actors have existed.
> 
> So when you see `exit_status` of publisher/merger/uploader/..., this is expected.
> 
> There is one log that I don't really like in your screenshot, this is the "Failed to replace splits". This kind of logs should not happen unless there is a bug somewhere or you removed manually a split for example. I cannot say much here as I would need the full history of the index. If you manage to reproduce this bug, it's worth opening an issue and put all the logs you have on this.
> 
> @yangjinming1062 if this explanation is sufficiently clear, let me know so that I can close the issue.

Thanks, this explanation is very sufficiently clear. Here is more logs 
[quickwit-202209282131.tar.gz](https://github.com/quickwit-oss/quickwit/files/9683290/quickwit-202209282131.tar.gz)
