### ISSUE TITLE
Improve GC performance

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#2126]
Splits sometimes need to be deleted:
- because they were replaced after a merge.
- because they were uploaded, but some failure prevented their publication. (In that case they are in the Staged state)
- because they only contain documents out of the retention period.

We do never delete splits right away, to avoid interferring with in-flight queries. Instead we change their state to MarkForDelete. The GC then periodically delete the splits that have been in the MarkForDelete splits for more than a given grace period.

Delete here means "delete them from the storage", then "delete them from the metastore".
The current GC is pretty much stateless. Periodically it wakes up, and queries the metastore. 

On a large volume (50 indexes) with partitioning, our current approach to GC has proved to be too inefficient.

There is a lot of room for improvement for our GC:
- push down the predicates that allow computing the list of splits candidate for deletion, add indexes, `SELECT split_id` etc.
- `LIMIT 100`?
- incremental GC
- batch delete request at the storage level

Also it would be very helpful to improve our observability.

**Comment by fulmicoton** [comment]
> Adding a limit and trying to incrementally run the deletes presents a difficult problem around how you actually catch up to the rate of deletes being produced, situations where you can catch up tend to not have the original performance issue in the first place although it probably wouldn't hurt to have, it doesn't solve the main issue which is the effects on other services when trying to keep up with a large number of deletes being produced at high load.

Right now the GC loop look like 

```
loop {
  gc()
  wait(duration)
}
```

it could be something like 
```
loop {
     let splits_to_gc_possibly_remaining = gc_with_limit();
     if !splits_to_gc_possibly_remaining {
         wait(duration)
     }
  }
}
```

**Comment by guilload** [comment]
A few things regarding optimizing our schema/indexes/triggers:
- there is a trigger that updates the index `update_timestamp` each time we update/delete a split; that might be the culprit.
- PostgreSQL supports partial indexes, we can add partial index on `split_state` for the `Staged` and `MarkForDeletion` states
- the `splits` table has no index on `index_id`; that's probably a must-have for deployments with many indexes.

**Comment by ChillFish8** [comment]
I've attempted both but neither seems to convince the query planner that it's worth using when working with index (maybe we can convince it if there's a high number? Will try that next) 😞 

```sql
delete from splits where split_state = 'MarkedForDeletion';
```

produces the following explanation, seemingly with and without the index being present:
![image](https://user-images.githubusercontent.com/57491488/196945799-cb3787f0-45fc-4f94-ab98-17bc82194419.png)

**Comment by guilload** [comment]
Yeah, it's only going to manifest with a high number of splits that span multiple pages, where few splits are marked for deletion and few pages contain splits marked for deletion. Tricky.

**Comment by ChillFish8** [comment]
While implementing the incremental GC plan, I noticed that we concurrently spawn a GC task for every index. This is fine for a small number of indexes (< 5 let's say) but I suspect that we're able to completely kill our connection pool with anything more than 10 indexes with this approach.

The issue is that our `MAX_CONCURRENT_STORAGE_REQUESTS` which is the maximum number of GC tasks we run concurrently, is `10` which also happens to be our **maximum** connection pool size, which means that the GC tasks alone can hold all of the pool connections at several points in time stalling the indexers or any services using the pool.

I suspect this is part of the reason why I'm unable to replicate stalls in the performance when using only a few indexes vs a large number like some of the setups reporting the issue.

I think it might be worth attempting to combine the GC instances into one for the whole store rather than for each index, which should overall reduce the contention and chances for stalling operations using the connection pool, and also reduce the number of operations we're issuing Postgres with.

**Comment by fmassot** [comment]
Good point. 

The way we currently solve this issue is by having one metastore node that makes queries to the database directly. Basically the cluster setup is like this:
- one metastore node (it's possible to have several but we don't have tested this setup yet)
- all other nodes make gRPC calls to the metastore node in order to query the database

This setup avoids opening too many db connections. 

That being said, we will certainly have scaling issues with thousands of indexes, we hope to test it soon :)

**Comment by ChillFish8** [comment]
I forgot about the gRPC system, but that raises another question of how suitable the gRPC is for large-scale systems where the load on a single megastore connection pool is now the choke point as such for all of the nodes using it - I think at larger scales it might actually be more suitable to have each node connecting to Postgres directly (pgbouncer would be useful in terms of Postgres setup) so that way nodes don't stall each other waiting on the 1 of the 10 connections.
