### ISSUE TITLE
Retention policy can potentially never delete some splits 

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2199]
If we take the case where:
- we continuously make delete operations on some splits
- or we make some merges during a very long time on some splits

The retention policy with its criteria based on the publish timestamp will delete such splits in a very long time.

By setting a retention of a period of X days, a user would expect that X days after the publication of the first split, it would be deleted, without taking into account merges or deletes.

This issue came up to my mind when thinking about persisting maturity in the metastore. Right now, I don't see how we can avoid storing the timestamp at which the documents come in quickwit. Maybe `indexing_timestamp` could be the name.

**Comment by evanxg852000** [comment]
@fmassot  @guilload 
After trying to see if we can do without adding new field:
1. I am thinking that the `publish_timestamp`  can play the same role as the new field we want to introduce `first_published_timestamp` , (potentially just rename it)
- During merge we just need keep the max `pusblish_timestamp`  
- During delete we keep the same  `pusblish_timestamp` 

The issue right now is that our metastore API does not expose a way to change the `publish_timestamp` . So this might be a lot of change we might not want.

2. Add the new field in SplitMetadata `first_published_timestamp: Option<i64>`.  
The issue is still how to update this value on the first publication of the Split since SplitMetadata is an opaque JSON.
My proposed solution is to avoid updating it when the split is first published. But derive it from `Split::pusblish_timestamp` if it's not set yet. This implies that for a split that has never gone through merge or delete, it's `first_published_timestamp` will be none so we can use the `Split::pusblish_timestamp` until it goes through merge or delete at which point a new Split is created with the  `first_published_timestamp`
In merge policy for instance that will result in:
```rust
let default_publish_timestamp = split.publish_timestamp;
let publish_timestamp = split.metadata.first_published_timestamp.unwrap_or(default_publish_timestamp);
retention_policy.is_eligible(publish_timestamp)
```

**Comment by fmassot** [comment]
With the solution of letting the `first_published_timestamp` empty if no merge/delete means that, in some cases, we will have splits with no `first_published_timestamp` which is weird. Handling this missing values in the code will be confusing too.

I see 3 possible solutions to this:

1. Let the metastore handle the `publish_timestamp` like today and also `first_publish_timestamp`. This means that `first_publish_timestamp` is set at the same time `publish_timestamp` is there is no replaced splits. If there is some replaced splits, then take the max of their publish timestamp. 

2. Let the metastore handle the `publish_timestamp` like today and add `first_publish_timestamp` in the split metadata. On first publish, the metastore will populate the right value inside of this. On a merge or delete, we can set the split metadata correctly when we stage the split.


The 3rd one is a bit different. As of today, the timestamps defined by the metastore `create_timestamp`, `udpate_timestamp` and `publish_timestamp` are some sort of "admin" timestamps that the client cannot control.
But we may want to add and define some timestamps on the client side, timestamps more useful from a functional point of view. I thought about the `last_indexed_doc_timestamp` that could be in the metadata.

**Comment by evanxg852000** [comment]
@fmassot  this can be closed right?

**Comment by fmassot** [comment]
yes!
