### ISSUE TITLE
Configurable output format for datetime and ip fields

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#2249]
The output format for the datetime field is a RFC3339 datetime string regardless of the input format. For IPs, the output format is ~~always IPV6~~. This makes these fields tricky to use.

Can we make the output formats configurable?

**Comment by evanxg852000** [comment]
Given IPs are internally store as Ipv6 and returned based on the possibility of extracting a valid `to_ipv4_mapped`.
https://github.com/quickwit-oss/tantivy/blob/main/src/schema/value.rs#L56-L63
We think in most use cases this is the correct thing to do rather than forcing on one output format. Maybe we could store with an IP tag on Tantivy.

**Comment by fulmicoton** [comment]
For the moment we are choosing not to store an extra information. On tantivy side we format as string all ip address that are ipv4

**Comment by guilload** [comment]
Closed via #2259 for the datetime field. The current behavior for the IP field seems ok.
