### ISSUE TITLE
We accept any string as datetime output format.

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2479]
For example `output_format: test` is valid :)

**Comment by fmassot** [comment]
@evanxg852000 can you handle this one?

**Comment by evanxg852000** [comment]
@fmassot  Not really sure if this is a bug, because of the way `strftime` parser works. 
Unless we want to check that at least one `strftime` special character should exist and preceded by `%` but with strftime I think the idea is the user can literally output what he wants. 
In the above example, the output for any datetime will be `test`

**Comment by fmassot** [comment]
This is a problem for me. Returning `test` for each timestamp is not a good behavior.
Moreover, if you write `unix_timestamp_seconds` instead of `unix_timestamp_secs`, quickwit will consider it valid.

**Comment by evanxg852000** [comment]
Ok my bad then, I should have mentioned this behavior when we agreed on introducing the `unix_timestamp_*` family of formats. Fixing it now.
