### ISSUE TITLE
Mutualize http connection pool when we have many s3-compatible storage. 

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#2593]
There are case where we will want thousands of indexes, all targetting a different storage, which are simply different bucket in the same S3-compatible storage.

In that case, we don't want 1000s of connection pool. We need a way to mutualize those.

**Comment by ChillFish8** [comment]
Is the issue here that we have thousands of HTTP connections or thousands of `S3CompatibleObjectStorage` ? 

If it's the former then this should already be handled by `hyper`'s internal connection pooling logic and should only create up to `n` concurrent connections where `n` is the number of concurrently running tasks trying to send a request, all we may need to do is have a `OnceCell` for the initial connector so that we're not re-creating the pool each time.

**Comment by fmassot** [comment]
@guilload: is it solved with the AWS SDK?

**Comment by guilload** [comment]
Yes, it is. See #3168.
