### ISSUE TITLE
Running two Pulsar pipelines with 2 indexers leads to duplicated documents

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2893]
**Describe the bug**

I ingested two times the [Stackoverflow dataset](https://quickwit-datasets-public.s3.amazonaws.com/stackoverflow.posts.transformed-10000.json) datasets (10 000 documents) with two indexers on an EKS cluster.

As mentioned in #2795, one indexer is indexing without failure but the second one keeps failing at publishing its splits because its checkpoints overlap with checkpoints already saved in the metastore by the other indexer.

**Steps to reproduce**
1. Start one indexer
2. Send messages
3. Start the second indexer
4. Wait until the end and get the document count in the UI, the number will be > 10 000.

This bug means that we may have missed something in Pulsar producer/consumer configuration or that we did not understand how it works with a consumer that keeps restarting.

Note: I indexed the dataset with 1 indexer only and got 10 000 documents exactly.

**Expected behavior**
Have 10 000 exactly at the end.

**Configuration:**

I open a PR #2892 to provide a Pulsar tutorial, you can follow it to reproduce: https://github.com/quickwit-oss/quickwit/pull/2892
You can execute `kubectl scale statefulsets testmain-quickwit-indexer --replicas=2` to add an indexer.

**Comment by ChillFish8** [comment]
Can I confirm that the first indexer never fails? Or that it does fail but keeps making progress?

**Comment by fmassot** [comment]
I think the first indexer never failed but I would need to do a proper check on this, it may have failed once or twice.

**Comment by fmassot** [comment]
Even if it's a bit different, I created a test in #2894 that reproduces the problem of duplicated indexed documents.

**Comment by ChillFish8** [comment]
Hmm this suggests that the ordering of the IDs is incorrect then otherwise we'd expect to get overlapping checkpoints.

**Comment by fmassot** [comment]
What do you mean by overlapping? Do you refer to the check made when publishing?

**Comment by ChillFish8** [comment]
yes, if we're having documents being duplicated (assuming pulsar isn't re-assigning message IDs) we'd expect the checkpoints to overlap

**Comment by fmassot** [comment]
In the test made in #2894 I don't publish anything. And even if I do the publish, only one source will do it. So if the source sends duplicates to the doc processor, we will publish a split with duplicates.

**Comment by ChillFish8** [comment]
Indeed it does re-produce the documents being re-sent, but under normal operations, if this occurred and we got duplicates we would expect the checkpoints for the splits to overlap.

`record_partition_delta` From what I understand should panic in this situation or if it's across multiple indexers it should fail when the indexers go to publish the split, either way I don't think it should be allowing messages with the same ID to be re-sent and re-indexed without erroring (which leads to the situation mentioned in the ticket where the resulting index contains duplicates)
the skipping logic is just to prevent panic rather than be an actual safe guard.

**Comment by fmassot** [comment]
Fixed by #2894
