### ISSUE TITLE
Should we switch docker-compose environment to listen on localhost by default?

### ISSUE THREAD

**Issue by imotov** [quickwit-oss/quickwit#3183]
As a follow up to #3177 I would like to see if anybody sees any issues with switching docker-compose to listen on localhost instead of 0.0.0.0 by default. We can control this with `.env` for example so switching back to listening on external interfaces should be possible without modifying docker-compose.yml file, but by default services will only be available to the host and not to the outside world.

**Comment by guilload** [comment]
I also favor using `127.0.0.1` by default instead of `0.0.0.0`.

However, one workflow that I enjoy is launching a local Quickwit node with `quickwit run ...` and the monitoring stack with `make docker-compose-monitoring` so I can access the dashboards/metrics of my local node. I suspect this relies on the listen host being `0.0.0.0`. I'd like to preserve that convenience.
