### ISSUE TITLE
Replace index_id with index_config_id in metastore methods

### ISSUE THREAD

**Issue by imotov** [quickwit-oss/quickwit#3231]
As a follow up to #3212 we should either remove index_id from metastore's stage_splits and publish_splits methods since it is already present in supplied split metadata or replace it with index_config_id for additional consistency checks.

**Comment by fulmicoton** [comment]
If it is painful, I think we can keep a redundant `index_id` or `index_config_id` argument.
It has the merit of informing the client that a given call can only target one index and not more.

We cannot handle calls targetting several indexes because the filebacked metastore cannot update several index atomically ((it's one file per index).
