### ISSUE TITLE
Document refresh query string paramater in ingest endpoint  

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3309]
It should show up here.
https://quickwit.io/docs/main-branch/reference/rest-api#ingest-data-with-elasticsearch-compatible-api

We also need to comment the code of the commit type enum in quickwit-ingest/src/lib.rs

Especially it is unclear whether WaitFor just waits or forces and wait.
(It would be great to be able to do both)

**Comment by imotov** [comment]
There is an explanation in https://quickwit.io/docs/main-branch/reference/rest-api#ingest-data-into-an-index which says:
"The wait_for parameter will cause the command to wait for the documents to be committed according to the standard time or number of documents rules." I am sorry if this was unclear, I will try to reformulate it. 

There is also a link to elasticsearch docs at the end of the first paragraph on https://quickwit.io/docs/main-branch/reference/rest-api#ingest-data-with-elasticsearch-compatible-api I didn't think any additional explanation is required since there is a pretty good explanation on the linked page.

I will add comments tomorrow.

**Comment by fulmicoton** [comment]
Aaaaah I see. I think it might be easier to follow the format of the rest of the API and show parameters in a table.

**Comment by fulmicoton** [comment]
Cool and so force is doing what i want!

**Comment by fulmicoton** [comment]
I does not seem to work however.

```
echo "Removing possibly existing gharchive index "
curl -s -X DELETE "localhost:7280/api/v1/indexes/gharchive" > /dev/null
echo "Creating gharchive index "
curl -s -X POST "localhost:7280/api/v1/indexes/" -H 'Content-Type: application/json' -d @quickwit-gharchive.json > /dev/null
echo "Ingesting data for gharchive"
gunzip -c gharchive-bulk.json.gz | curl -s -X POST "localhost:7280/api/v1/_bulk?refresh=force" -H 'Content-Type: application/json' --data-binary @- > /dev/null
```

Does not seem to have the documents available when it ends.

**Comment by imotov** [comment]
For historical reasons it is `?refresh`  or `?refresh=true` in [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html).

**Comment by imotov** [comment]
In any case, I will rework documentation. If it wasn't clear for you, I don't think it is reasonable to expect users to read and understand that wall of text.

**Comment by fulmicoton** [comment]
Ah yes! I forgot I was using the elastic bulk API instead of the regular ingest API. Sorry for the noise.
m( _ _ )m
