### ISSUE TITLE
Support index deletes with an index pattern

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3841]
[elasticsearch muti target doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/api-conventions.html#api-multi-index)

[elastic index delete API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-index.html#delete-index-api-path-params)

This feature should be first implemented in the elasticsearch compatible API (under `_elastic`).

Additional notes:
- The delete with index patterns containing wildcards should not be enabled by default. It is ok to give a list of index IDs.
- We should return an elasticsearch-like response.

**Comment by matthewfollegot** [comment]
👋  Hello @fmassot, I was looking into potentially picking this up, what's the status with this issue?

**Comment by fmassot** [comment]
@matthewfollegot cool! We have a small time constraint on it; if you can't work on it in the following days (some work was also done on it in a PR), we can find you another issue.

**Comment by matthewfollegot** [comment]
I started on this and should be able to make more progress tomorrow.
Just a question for you in the meantime: would you prefer this to be a separate endpoint than the `DELETE "/indexes/{index_id}"` endpoint? I think it would be cleaner than separating it out into its own, but this would make this endpoint slower because we'd have to submit a search query for each pattern. An improvement would be to only search if it contains certain characters (e.g. `*`, `.`, but we'd still have to search over patterns that include these.

**Comment by esatterwhite** [comment]
I think this should support at least the `timeout` and `ignore_unavailable` query params.

if `ignore_unavailable` is set to `true` it shouldn't be considered a success if the index in question is missing rather than 404.
