### ISSUE TITLE
Question on `handle_unavailable_leaders` logic

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4267]
`handle_unavailable_leaders` seems to mark as Unavailable shards with an unavailable leader.

Is this correct? I thought unavailable was also a read state, in which case a replica would be sufficient to allow its consumption.

**Comment by guilload** [comment]
> `handle_unavailable_leaders` seems to mark as Unavailable shards with an unavailable leader.
Yes.

Routers report unavailable leaders from their point of view to the control plane. If the control plane agrees, it marks the shards owned by the leaders as `Unavailable`, so they are no longer advertised to other routers.

> I thought unavailable was also a read state, in which case a replica would be sufficient to allow its consumption.

I don't understand what you mean, but here is what I can say. From a consumption perspective, we should still schedule unavailable shards since fetch streams will attempt to read from a leader or follower and retry indefinitely if any error occurs.

**Comment by guilload** [comment]
This logic no longer exists.
