### ISSUE TITLE
Ingest v2: Investigate why we can't ingest more than 15MB/s on a single index

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4787]
In ingest v2, we seem to not be able to ingest more than 15MB/s on a single index. The cause is currently unknown.
It can be reproduced with simian.

The behavior we would be expecting is the following:
Ingester are reporting the throughput they receive for each of their shard. If a threshold is met, the control plane will add a  new shard. This is done every 5s or so. 
One shard can only receive 5MB/s at most.

**Comment by guilload** [comment]
> This is done every 5s or so.
Note that opening shards is rate-limited to 1 shard/min per index.

**Comment by trinity-1686a** [comment]
at first glance, i can't reproduce. The ramp-up isn't instantaneous (probably the 1opening per min), but i do ramp up to close to 100MiBs on my laptop, 1 all-purpose node, 1 index.  (the dip in the middle is because i fed too little docs at start)

![image](https://github.com/quickwit-oss/quickwit/assets/35889323/3b252afd-5df9-4214-89d1-6512446215fe)

**Comment by fulmicoton** [comment]
> Note that opening shards is rate-limited to 1 shard/min per index.

@guilload oh really?

**Comment by trinity-1686a** [comment]
I suspect the issue might be with simian. I can reproduce on gke, and locally with simian. With a single `chico(rate=160mb)`, i get stuck at 16-17MiB/s.
However if i modify simian to have a group of `chico(rate=10mb)*16` hitting the same index, I can reach 100+MiB/s on a single node locally (not tested on gke)

**Comment by trinity-1686a** [comment]
the client was using an incorrectly configured token bucket, where burst ended up being lower than rate in some cases
