### ISSUE TITLE
Failure to parse query with special characters via Elasticsearch search endpoints

### ISSUE THREAD

**Issue by esatterwhite** [quickwit-oss/quickwit#5089]
**Describe the bug**
In a json string, the escape character also has to be escaped for it to be transmitted correctly, but this creates a parsing error.

##### Query Payload
```json5
{
  "size": 0,
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "fields": [
              "program"
            ],
            "query": "vector\\:\\:sources\\:\\:kafka*",
            "lenient": true
          }
        }
      ]
    }
  }
}
```
##### Response Payload
```json5
{
  "status": 400,
  "error": {
    "caused_by": null,
    "reason": "failed to parse query: `vector\\:\\:sources\\:\\:kafka*`",
    "stack_trace": null,
    "type": null
  }
}
```

**Expected behavior**
The query should be parsed as an escaped colon `:` as described in the docs for [escaping special characters](https://quickwit.io/docs/reference/query-language#escaping-special-characters)  `vector\:\:sources\:\:kafka*`

**Comment by esatterwhite** [comment]
> fixed in [quickwit-oss/tantivy#2416](https://github.com/quickwit-oss/tantivy/pull/2416), we still have to update the tantivy used in quickwit

Thank you!

**Comment by trinity-1686a** [comment]
hum, actually there might be a 2nd issue, but I'm not entirely sure.
The tantivy patch fixes the error you get and https://github.com/quickwit-oss/quickwit/issues/5041 returning everything, but then in both case we return nothing because we consider the entire thing as a wildcard query, which doesn't get tokenized.
I've checked what ES does, and in both case it doesn't find any matches, so it seems it doesn't tokenize wildcard queries either.

Is that the result you expect?

**Comment by esatterwhite** [comment]
No, elastic definitely returns the results matching only the query.

in elastic, we have `program` mapped as a keyword field w/ a lower case normalizer. And in quickwit, a text field, with a raw tokenizer + lowercase normalizer.

**Comment by trinity-1686a** [comment]
oh okay. that field uses the raw tokenizer, then not tokenizing is what should happen indeed

**Comment by esatterwhite** [comment]
The documents have a field like this

```json5
  "program": "vector::sources::kafka"
```
