### ISSUE TITLE
Investigate security considerations on the local file storage

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#53]
The URI resolution scheme for the file system can have some important risk implication.
We also want to handle file:///var/local and the incorrect but common file://var/local format. 

We need to make sure someone cannot access files that are not under the root directory using the "../" schemefor instnace.

Generally speaking: we should put some thoughts in it. 

----

UPDATE:

We want to enforce the fact that path accessed by the FileStorage are child path of the FileStorage root.

**Comment by fulmicoton** [comment]
(As far as I could tell #61 is not solving this bug.)

**Comment by fmassot** [comment]
> We also want to handle file:///var/local and the incorrect but common file://var/local format.
`file://var/local` currently works but `var/local` is interpreted as a variable path. 
I think we can consider that `file://var/local` be the same `file:///var/local'

Concerning security issues on path, I think we can simply ban the use of `..`. We accept only absolute path without parent directory so that when we manipulate path inside quickwit there is no suprise.
