### ISSUE TITLE
Jaeger api min\max Duration filters isn't working

### ISSUE THREAD

**Issue by kuzaxak** [quickwit-oss/quickwit#5441]
**Describe the bug**

When using Jaeger compatible endpoint `/api/traces?service=sync-service&minDuration=1000us&start=1727085837007000&end=1727107437007000&lookback=custom` no data returned.

At the same time if I specify any value in maxDuration I receive traces way longer that I limited.

**Steps to reproduce (if applicable)**

1. Collect some traces
2. Call Jaeger search endpoint with min or max filter parameters passed
3. Get the data which is not filtered or empty

<img width="810" alt="SCR-20240923-quvh" src="https://github.com/user-attachments/assets/fb7ced33-5992-4b45-9257-4a62517aec6e">

**Expected behavior**

min \ max filter should be applied to traces stored.

**Configuration:**
Please provide:

1. Output of `quickwit --version`
  ```
  Quickwit 0.8.0 (aarch64-unknown-linux-gnu 2024-09-20T09:00:32Z 634a1bc)
  ```
2. I'm using system `otel-traces-v0_9` index

**Comment by guilload** [comment]
Hi @kuzaxak, I have identified the issue. I'm working on a fix.

**Comment by guilload** [comment]
It turns out it's not a bug; it's a feature... This is how trace search works for various Jaeger backends (ClickHouse, Elasticsearch, Quickwit, ...).

A trace search query contains the following parameters:
- `service_name`
- `operation_name`
- `tags` (map<str, str>)
- `start_time_min`
- `start_time_max`
- `duration_min`
- `duration_max`
- `num_traces`

Backends flatten traces and store them as a table of spans. A trace matches the query if any of its spans matches the query. In pseudo-SQL, this is equivalent to:
```sql
SELECT DISTINCT trace_id
FROM spans as s
WHERE
	s.service_name = q.service_name AND 
	s.span_name = q.operation_name AND
	s.start_timestamp >= q.start_time_min AND
	s.start_timestamp <= q.start_time_max AND
	s.duration >= q.duration_min AND
	s.duration <= q.duration_max
ORDER BY service, start_timestamp DESC
LIMIT q.num_traces
```

Since a trace is comprised of multiple, potentially non-overlapping spans,  `span.duration <= q.duration_max` does not necessarily imply `trace.duration <= q.duration_max`. This is also true for `duration_min` and `start_time_min/max`.

This spec is clearly outlined in [query.proto](https://github.com/jaegertracing/jaeger-idl/blob/main/proto/api_v2/query.proto#L78-L111):
> Query parameters to find traces. Except for num_traces, all fields should be treated as forming a conjunction, e.g., "service_name='X' AND operation_name='Y' AND ...". All fields are matched against individual spans, not at the trace level. The returned results contain traces where at least one span matches the conditions.

We were also able to reproduce the behavior you observed with the default Jaeger backend. You can clearly see that the filter is applied on spans, otherwise the trace wouldn't match:

![image (1)](https://github.com/user-attachments/assets/885b9a50-2c5e-4436-b253-06226877de1c)


See also:
[CH impl](https://github.com/jaegertracing/jaeger-clickhouse/blob/main/storage/clickhousespanstore/reader.go#L333)
[ES impl](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/es/spanstore/reader.go#L513)

We will eventually document this behavior in our docs. I hope this helps.
