### ISSUE TITLE
Add StackOverflow dataset for testing/tutorial purpose

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#812]
I put a first version here: https://quickwit-datasets-public.s3.amazonaws.com/stackoverflow.posts.json.gz

This is a ndjson file with document like:

```json
{
	"user": "45",
	"tags": ["c#", "linq", ".net-3.5"],
	"questionId": "59",
	"creationDate": "2008-08-01T13:14:33.797",
	"title": "How do I get a distinct, ordered list of names from a DataTable using LINQ?",
	"acceptedAnswerId": "43110",
	"type": "question",
	"body": "Let's say I have a DataTable with a Name column. I want to have a collection of the unique names ordered alphabetically. The following query ignores the order by clause. var names = (from DataRow dr in dataTable.Rows orderby (string)dr[\"Name\"] select (string)dr[\"Name\"]).Distinct(); Why does the orderby not get enforced? "
}
```

To be more quickwit friendly, we need to transform some data like ids and the creation date.

**Comment by imotov** [comment]
I have been playing with this dataset for a bit by using a very small jq script that converts the record above into
```json
{
	"user": 45,
	"tags": ["c#", "linq", ".net-3.5"],
	"questionId": 59,
	"creationDate": "2008-08-01T13:14:33Z",
	"title": "How do I get a distinct, ordered list of names from a DataTable using LINQ?",
	"acceptedAnswerId": 43110,
	"type": "question",
	"body": "Let's say I have a DataTable with a Name column. I want to have a collection of the unique names ordered alphabetically. The following query ignores the order by clause. var names = (from DataRow dr in dataTable.Rows orderby (string)dr[\"Name\"] select (string)dr[\"Name\"]).Distinct(); Why does the orderby not get enforced? "
}
```

The script is 

```bash
jq -c '
    .user=(.user|tonumber) | 
    .questionId=(.questionId|tonumber) | 
    if .acceptedAnswerId then .acceptedAnswerId=(.acceptedAnswerId|tonumber) else . end | 
    .creationDate=(.creationDate[:-4]+"Z")
'
```
I can upload the processed file somewhere if that would be easier for you. 

I also think that a smaller subset of this dataset could be a great dataset to use in #1618, it has pretty much everything (except maybe json) to show off the current set of features in quickwit including timestamp based search and aggregations.

**Comment by fmassot** [comment]
@imotov nice, I would be happy to update our S3 dataset with yours, and indeed, it would be nice to have it on the quickstart page.

**Comment by guilload** [comment]
I'm about to revive the VRL branch (#2555), so the transformation can be performed natively in Quickwit.

**Comment by imotov** [comment]
Hmm, maybe we can do both. I think converting these 4 fields might be too much processing for the getting started page. Since “you never get a second chance to make a first Impression” having a dynamic and exciting getting started page is crucial. Coming from Elasticsearch, converting json strings to numbers just doesn’t excite me that much since Elasticsearch does this by default (it can be disabled with `coerce` flag in mapping). I feel that adding this part into getting started guide might bog down the reader with unnecessary details. What would excite me though is to do some additional transformation in VRL like calculating some metric on the text (length or word count for example) and then show it off in aggregation. First thing that comes to mind is to show how to find tags associated with the most (or the least) verbose answers on average. In other words, I think that for the getting started page it would be great to demonstrate VRL as add-on functionality instead of using it as a workaround for strange data. In more detailed tutorials, showing some ways to transfer data in bad format on the way in would be really helpful.

**Comment by guilload** [comment]
I agree with you :)

**Comment by imotov** [comment]
@fmassot here is the transformed dataset:
https://f000.backblazeb2.com/file/transport-public/stackoverflow.posts.transformed.json.gz

I also created a smaller version with the first 10000 records:
https://f000.backblazeb2.com/file/transport-public/stackoverflow.posts.transformed-10000.json

I tested the bigger dataset with the following index settings:
https://f000.backblazeb2.com/file/transport-public/stackoverflow.yaml

I will open PR with changes to getting started guide in a bit. But here are some fun queries we could mention there:

What are the top 10 tags related to "rust":
```
curl -XPOST localhost:7280/api/v1/stackoverflow/search -H 'Content-Type: application/json' -d '{
    "query": "tags:rust",
    "max_hits": 1,
    "aggs":
    {
        "rust_related_tags":
        {
            "terms":
            {
                "field": "tags",
                "size": 10
            }
        }
    }
}'
```

What topics were users happy about:
```
curl -XPOST localhost:7280/api/v1/stackoverflow/search -H 'Content-Type: application/json' -d '{
    "query": "body:happy",
    "max_hits": 0,
    "aggs":
    {
        "happy_tags":
        {
            "terms":
            {
                "field": "tags",
                "size": 10
            }
        }
    }
}'
```
It's fun list, but I wouldn't read too much into it since it most likely just reflects frequency of questions on these topics. If you replace "happy" with "frustrating" the top 10 almost doesn't change with the exception of "ios" tag replacing "c++", which somewhat matches my experience in the last 8 months 😄. We need a `significant_terms` aggregation to make this example truly interesting.

Who was the most prolific answerer who mention rust in their answers?
```
curl -XPOST localhost:7280/api/v1/stackoverflow/search -H 'Content-Type: application/json' -d '{
    "query": "body:rust AND type:answer",
    "max_hits": 0,
    "aggs":
    {
        "rust_answerers":
        {
            "terms":
            {
                "field": "user",
                "size": 10
            }
        }
    }
}'
```

Unfortunately, when I tried to run this aggregation on the entire dataset I got an error message "Aborting aggregation because too many buckets were created". It seems like we could apply some optimization there since we are only asking for 15 buckets per split.

**Comment by fmassot** [comment]
This is very interesting, thanks! I’m going to upload your datasets very soon. @PSeitz can you have a look at the aggregation query?

**Comment by fmassot** [comment]
@imotov datasets uploaded here:
- [stackoverflow.posts.transformed.json.gz](https://quickwit-datasets-public.s3.amazonaws.com/stackoverflow.posts.transformed.json.gz)
- [stackoverflow.posts.transformed-10000.json](https://quickwit-datasets-public.s3.amazonaws.com/stackoverflow.posts.transformed-10000.json)

**Comment by PSeitz** [comment]
We have a limit on the buckets set to `65000`. The limit is shared between bucket aggregations within a request.

https://github.com/quickwit-oss/quickwit/blob/main/quickwit/quickwit-search/src/collector.rs#L314

For the terms aggregation we could circumvent this limit, by periodically removing the N lowest counts.

**Comment by imotov** [comment]
@fmassot could you make these files publicly readable?

**Comment by imotov** [comment]
@fmassot actually please wait a bit with it. I just discovered that I missed a field during the conversion. Let me regenerate the file and re-upload it again.

**Comment by imotov** [comment]
@fmassot I have uploaded the new versions to the same location. Could you re-upload them to S3 and fix permissions, please? Thanks!

**Comment by fmassot** [comment]
@imotov should be good now

**Comment by imotov** [comment]
@fmassot Thanks! It seems to work. I opened #2725 that replaces wikipedia with stackoverflow. Not sure if we can consider this issue done or if you also want to create a more detailed tutorial that uses this dataset.

**Comment by fmassot** [comment]
Quickstart updated: https://quickwit.io/docs/get-started/quickstart
Thanks!
