### ISSUE TITLE
The kafka source does not allow us to select a subset of the partitions

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#959]

**Comment by guilload** [comment]
That limitation comes from the `SourceFactory` API:
```
async fn typed_create_source(
        params: KafkaSourceParams,
        checkpoint: Checkpoint,
) -> anyhow::Result<Self::Source> {
```

With that, you can't infer which partitions the source has to index since the checkpoint potentially does not contain partitions that have been newly added and we don't know about.

We could:
- only index partitions in the checkpoint and ensure new partitions appear as `PartitionId -> Position::Beginning`
- or, pass an additional parameter such as `PartitionSet`:

```rust
pub enum PartitionSet {
  All,
  Subset(Vec<PartitionID>)
}

**Comment by guilload** [comment]
That's no longer needed. Instead, we rely on Kafka consumer groups to distribute subsets of partitions to consumers.
